version: "3.8"

services:
  redis:
    image: redis:6.0-buster
    ports:
      - "6379:6379"
    restart: always
    command: >
      --requirepass "mypassword"
    networks:
      - fullstack

  ratelimit:
    build: .
    container_name: "ratelimit"
    ports:
      - "8080:8080"
    depends_on:
      - redis
    restart: always
    networks:
      - fullstack

networks:
  fullstack:
    driver: bridge